In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [5]:
df.shape

(5572, 3)

In [6]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [9]:
X_test.shape

(1115,)

In [10]:
type(X_train)

pandas.core.series.Series

In [11]:
X_train[:4]

5050    Edison has rightly said, "A fool can ask more ...
1174                            Ü dun need to pick ur gf?
2915    Sorry! U can not unsubscribe yet. THE MOB offe...
4424    alright. Thanks for the advice. Enjoy your nig...
Name: Message, dtype: object

In [12]:
type(y_train)

pandas.core.series.Series

In [13]:
y_train[:4]

5050    0
1174    0
2915    1
4424    0
Name: spam, dtype: int64

In [14]:
type(X_train.values)

numpy.ndarray

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59301 stored elements and shape (4457, 7798)>

In [16]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
X_train_cv.shape

(4457, 7798)

In [18]:
v.get_feature_names_out()[1771]

'cheetos'

In [19]:
v.vocabulary_

{'edison': 2543,
 'has': 3354,
 'rightly': 5817,
 'said': 5915,
 'fool': 2944,
 'can': 1632,
 'ask': 1099,
 'more': 4605,
 'questions': 5551,
 'than': 6845,
 'wise': 7585,
 'man': 4354,
 'answer': 985,
 'now': 4858,
 'you': 7760,
 'know': 3979,
 'why': 7550,
 'all': 912,
 'of': 4909,
 'us': 7262,
 'are': 1055,
 'speechless': 6400,
 'during': 2506,
 'viva': 7365,
 'gm': 3167,
 'gn': 3169,
 'ge': 3106,
 'gnt': 3171,
 'dun': 2500,
 'need': 4746,
 'to': 6983,
 'pick': 5222,
 'ur': 7250,
 'gf': 3137,
 'sorry': 6359,
 'not': 4844,
 'unsubscribe': 7227,
 'yet': 7746,
 'the': 6858,
 'mob': 4560,
 'offer': 4916,
 'package': 5063,
 'min': 4500,
 'term': 6816,
 '54': 550,
 'weeks': 7491,
 'pls': 5280,
 'resubmit': 5787,
 'request': 5756,
 'after': 850,
 'expiry': 2738,
 'reply': 5749,
 'themob': 6869,
 'help': 3412,
 'info': 3690,
 'alright': 925,
 'thanks': 6848,
 'for': 2952,
 'advice': 833,
 'enjoy': 2618,
 'your': 7766,
 'night': 4796,
 'out': 5028,
 'ma': 4306,
 'try': 7106,
 'get': 3127,
 'some': 6329,
 'sleep': 6253,
 'am': 935,
 'it': 3777,
 'hurt': 3579,
 'chance': 1727,
 'be': 1278,
 'on': 4953,
 'reality': 5631,
 'fantasy': 2794,
 'show': 6164,
 'call': 1609,
 '08707509020': 91,
 'just': 3896,
 '20p': 360,
 'per': 5166,
 'ntt': 4866,
 'ltd': 4269,
 'po': 5289,
 'box': 1464,
 '1327': 294,
 'croydon': 2098,
 'cr9': 2067,
 '5wb': 562,
 '0870': 72,
 'is': 3765,
 'national': 4722,
 'rate': 5599,
 'how': 3539,
 'miss': 4526,
 'house': 3534,
 'maid': 4335,
 'murderer': 4671,
 'coz': 2062,
 'was': 7439,
 'murdered': 4670,
 'lt': 4268,
 'gt': 3271,
 'th': 6844,
 'january': 3815,
 'as': 1089,
 'public': 5507,
 'holiday': 3482,
 'govt': 3221,
 'instituitions': 3719,
 'closed': 1857,
 'including': 3667,
 'post': 5349,
 'office': 4920,
 'understand': 7193,
 'fighting': 2852,
 'with': 7594,
 'world': 7644,
 'easy': 2530,
 'either': 2568,
 'win': 7567,
 'or': 4993,
 'lose': 4226,
 'bt': 1549,
 'fightng': 2853,
 'some1': 6330,
 'who': 7543,
 'close': 1855,
 'dificult': 2331,
 'if': 3618,
 'still': 6518,
 'lol': 4204,
 'no': 4813,
 'ouch': 5025,
 'but': 1579,
 'wish': 7586,
 'stayed': 6495,
 'bit': 1378,
 'longer': 4212,
 'they': 6883,
 'finally': 2869,
 'came': 1628,
 'fix': 2895,
 'ceiling': 1705,
 'sounds': 6371,
 'good': 3198,
 'keep': 3927,
 'me': 4425,
 'posted': 5353,
 'll': 4180,
 'always': 933,
 'there': 6875,
 'even': 2675,
 'its': 3784,
 'in': 3659,
 'spirit': 6416,
 'bb': 1261,
 'soon': 6350,
 'trying': 7108,
 'sure': 6672,
 'huh': 3563,
 'cant': 1644,
 'thk': 6899,
 'oredi': 5004,
 'many': 4366,
 'pages': 5067,
 'do': 2384,
 'we': 7464,
 'have': 3367,
 'yes': 7743,
 'he': 3378,
 'really': 5635,
 'great': 3248,
 'bhaji': 1350,
 'told': 7000,
 'kallis': 3910,
 'best': 1335,
 'cricketer': 2092,
 'sachin': 5904,
 'very': 7324,
 'tough': 7048,
 'isn': 3772,
 'frnd': 3021,
 'necesity': 4739,
 'life': 4120,
 'imagine': 3635,
 'urself': 7261,
 'witout': 7600,
 'hw': 3588,
 'feel': 2822,
 'at': 1122,
 'colleg': 1907,
 'wat': 7444,
 'wth': 7681,
 'cell': 1711,
 'abt': 764,
 'functions': 3052,
 'thnk': 6901,
 'events': 2679,
 'espe': 2657,
 'cared': 1658,
 'missed': 4528,
 'amp': 950,
 'irritated': 3760,
 '4wrd': 530,
 'those': 6905,
 'dear': 2211,
 'loving': 4255,
 'frnds': 3022,
 'wthout': 7682,
 'whom': 7546,
 'live': 4172,
 'jst': 3881,
 'did': 2315,
 'takecare': 6737,
 'goodmorning': 3203,
 'ok': 4936,
 'lar': 4030,
 'double': 2436,
 'check': 1759,
 'wif': 7555,
 'da': 2160,
 'hair': 3309,
 'dresser': 2462,
 'already': 924,
 'wun': 7688,
 'cut': 2148,
 'short': 6149,
 'will': 7564,
 'until': 7230,
 'look': 4214,
 'nice': 4790,
 'gain': 3071,
 'rights': 5818,
 'wife': 7556,
 'dont': 2422,
 'demand': 2260,
 'husband': 3582,
 'too': 7023,
 'lets': 4105,
 'see': 6020,
 'whatsup': 7524,
 'want': 7427,
 'neva': 4773,
 'mind': 4503,
 'den': 2261,
 'only': 4964,
 'weekdays': 7487,
 'got': 3213,
 'special': 6392,
 'price': 5426,
 'haiz': 3313,
 'eat': 2531,
 'liao': 4111,
 'nails': 4699,
 'oso': 5017,
 'muz': 4682,
 'wait': 7404,
 'finish': 2877,
 'drivin': 2469,
 'lunch': 4280,
 'afternoon': 852,
 'my': 4684,
 'love': 4245,
 'any': 996,
 'job': 3854,
 'prospects': 5487,
 'missing': 4530,
 'what': 7521,
 'being': 1317,
 'lazy': 4060,
 'and': 963,
 'bleak': 1395,
 'hmmm': 3467,
 'happy': 3346,
 'filled': 2860,
 'liked': 4130,
 'new': 4777,
 'dude': 2492,
 'haircut': 3310,
 'breezy': 1511,
 'up': 7232,
 'fine': 2874,
 'absolutly': 762,
 'tell': 6800,
 'whos': 7547,
 'this': 6898,
 'lor': 4225,
 'msg': 4636,
 'b4': 1185,
 'welp': 7504,
 'apparently': 1022,
 'retired': 5793,
 'ew': 2704,
 'one': 4958,
 'them': 6867,
 'so': 6316,
 'li': 4110,
 'hai': 3307,
 'bored': 1445,
 'lecturer': 4084,
 'repeating': 5742,
 'last': 4037,
 'stuff': 6583,
 'waste': 7441,
 'time': 6948,
 'thinkin': 6892,
 'malaria': 4349,
 'relax': 5705,
 'children': 1792,
 'handle': 3323,
 'she': 6110,
 'would': 7658,
 'been': 1300,
 'worse': 7650,
 'gastroenteritis': 3090,
 'takes': 6739,
 'enough': 2624,
 'replace': 5744,
 'her': 3423,
 'loss': 4230,
 'temp': 6806,
 'reduce': 5676,
 'give': 3154,
 'meds': 4441,
 'vomit': 7374,
 'self': 6035,
 'limiting': 4139,
 'illness': 3629,
 'which': 7537,
 'means': 4432,
 'few': 2838,
 'days': 2202,
 'completely': 1944,
 'stop': 6531,
 'ill': 3628,
 'drink': 2463,
 'pa': 5060,
 'then': 6870,
 'doing': 2408,
 'srs': 6454,
 'model': 4574,
 'send': 6046,
 'mail': 4336,
 'id': 3607,
 'that': 6855,
 'alrite': 926,
 'girl': 3148,
 'gail': 3069,
 'wrong': 7674,
 'take': 6736,
 'care': 1656,
 'sweet': 6698,
 'don': 2418,
 'worry': 7648,
 'l8tr': 4000,
 'hun': 3568,
 'yaxxx': 7728,
 'home': 3487,
 'awake': 1173,
 'kiss': 3966,
 'should': 6157,
 'chicken': 1785,
 'broth': 1534,
 'ramen': 5588,
 'unless': 7216,
 'about': 757,
 'hey': 3432,
 'mate': 4398,
 'spoke': 6428,
 'mag': 4325,
 'people': 5164,
 're': 5614,
 'deliver': 2253,
 'by': 1594,
 'end': 2602,
 'month': 4598,
 '24th': 372,
 'sept': 6058,
 'talk': 6744,
 'later': 4043,
 'sen': 6045,
 'going': 3186,
 'join': 3862,
 'his': 3452,
 'uncle': 7183,
 'finance': 2870,
 'cbe': 1697,
 'turn': 7128,
 'heater': 3397,
 'set': 6068,
 'degrees': 2244,
 'slaaaaave': 6249,
 'where': 7531,
 'must': 4677,
 'summon': 6644,
 'come': 1917,
 'own': 5053,
 'anymore': 999,
 'waliking': 7411,
 'ard': 1054,
 'wan': 7422,
 'buy': 1583,
 'anything': 1005,
 'go': 3173,
 'promotion': 5476,
 'number': 4871,
 '8714714': 688,
 'awarded': 1175,
 'city': 1824,
 'break': 1499,
 'could': 2045,
 '200': 350,
 'summer': 6642,
 'shopping': 6146,
 'spree': 6442,
 'every': 2682,
 'wk': 7603,
 'txt': 7143,
 'store': 6541,
 '88039': 693,
 'skilgme': 6238,
 'tscs087147403231winawk': 7113,
 'age16': 860,
 '50perwksub': 541,
 'nope': 4832,
 'thats': 6857,
 'might': 4492,
 'nap': 4713,
 'tho': 6904,
 'emigrated': 2595,
 'something': 6338,
 'maybe': 4418,
 '30': 430,
 'hopeful': 3506,
 'also': 927,
 'knows': 3981,
 'menu': 4468,
 'marvel': 4386,
 'mobile': 4562,
 'play': 5263,
 'official': 4922,
 'ultimate': 7171,
 'spider': 6411,
 'game': 3076,
 '50': 532,
 'right': 5815,
 'text': 6831,
 '83338': 661,
 'free': 2993,
 '8ball': 712,
 'wallpaper': 7418,
 'romcapspam': 5849,
 'everyone': 2687,
 'around': 1074,
 'responding': 5778,
 'well': 7502,
 'presence': 5410,
 'since': 6209,
 'warm': 7433,
 'outgoing': 5033,
 'bringing': 1522,
 'real': 5626,
 'breath': 1505,
 'sunshine': 6654,
 'voicemail': 7372,
 'please': 5272,
 '08719181503': 155,
 'cool': 2017,
 'fun': 3050,
 'practicing': 5377,
 'making': 4348,
 'babies': 1194,
 'mmmm': 4550,
 'fuck': 3037,
 'fair': 2773,
 'weaknesses': 7466,
 'grins': 3257,
 'pushes': 5528,
 'knee': 3973,
 'exposes': 2744,
 'belly': 1323,
 'pulls': 5513,
 'head': 3379,
 'forget': 2960,
 'yours': 7770,
 'wicked': 7551,
 'smile': 6286,
 'other': 5019,
 'mmm': 4549,
 'better': 1341,
 'roast': 5835,
 'down': 2442,
 'had': 3302,
 'drinks': 2466,
 'indian': 3681,
 'realise': 5628,
 'busy': 1578,
 'guy': 3293,
 'bother': 1454,
 'exams': 2709,
 'outta': 5040,
 'way': 7459,
 'cars': 1673,
 'gr8': 3224,
 'day': 2201,
 'smaller': 6277,
 'capacity': 1647,
 'quite': 5556,
 'ex': 2705,
 'boytoy': 1484,
 'happened': 3338,
 'yeah': 7731,
 'leave': 4079,
 'babe': 1192,
 'talking': 6747,
 'think': 6890,
 'boy': 1479,
 'everything': 2691,
 'an': 958,
 'idiot': 3613,
 'bak': 1211,
 'girlie': 3150,
 'arun': 1088,
 'transfr': 7071,
 'amt': 955,
 've': 7312,
 'gone': 3194,
 'place': 5250,
 'tomorrow': 7010,
 'coffee': 1891,
 'run': 5890,
 'tomo': 7008,
 'believe': 1318,
 'week': 7486,
 'forwarded': 2976,
 'from': 3029,
 '21870000': 362,
 'hi': 3435,
 'mailbox': 4337,
 'messaging': 4477,
 'sms': 6297,
 'alert': 900,
 'messages': 4476,
 '21': 361,
 'matches': 4397,
 'back': 1200,
 '09056242159': 174,
 'retrieve': 5794,
 'pay': 5140,
 'agree': 869,
 'much': 4653,
 'willing': 7565,
 'reason': 5640,
 'spoken': 6429,
 'year': 7732,
 'anyways': 1009,
 'exam': 2708,
 'sometimes': 6340,
 'slow': 6271,
 'gentle': 3117,
 'sonetimes': 6344,
 'rough': 5858,
 'hard': 3347,
 'meeting': 4445,
 'darlin': 2184,
 'supose': 6661,
 'film': 2863,
 'babysit': 1198,
 'again': 857,
 'xx': 7704,
 'height': 3403,
 'confidence': 1967,
 'aeronautics': 836,
 'professors': 5460,
 'wer': 7510,
 'calld': 1615,
 'askd': 1100,
 'sit': 6224,
 'aeroplane': 837,
 'aftr': 855,
 'sat': 5948,
 'dat': 2191,
 'plane': 5256,
 'ws': 7677,
 'made': 4322,
 'their': 6864,
 'students': 6578,
 'dey': 2299,
 'hurried': 3577,
 'didnt': 2318,
 'move': 4624,
 'wont': 7628,
 'start': 6481,
 'datz': 2198,
 'pass': 5118,
 '69669': 584,
 'collect': 1903,
 'polyphonic': 5320,
 'ringtones': 5824,
 'normal': 4838,
 'gprs': 3222,
 'charges': 1740,
 'apply': 1030,
 'tones': 7013,
 'took': 7024,
 'morphine': 4611,
 'yo': 7755,
 'kate': 3918,
 'evening': 2676,
 'hope': 3504,
 'bloody': 1407,
 'babyjontet': 1197,
 'xxx': 7707,
 'west': 7514,
 'coast': 1881,
 'forever': 2957,
 'today': 6989,
 'sunday': 6648,
 'work': 7638,
 'packing': 5064,
 'car': 1652,
 'let': 4104,
 'room': 5851,
 'welcome': 7500,
 'uk': 7168,
 'date': 2193,
 'giving': 3157,
 'calling': 1622,
 '08719839835': 157,
 'future': 3062,
 'mgs': 4484,
 'billed': 1362,
 '150p': 305,
 'daily': 2167,
 'cancel': 1636,
 '89123': 706,
 'done': 2420,
 'internet': 3731,
 'connection': 1980,
 'first': 2889,
 'thing': 6888,
 'dislikes': 2365,
 'bed': 1293,
 'ya': 7716,
 'telling': 6801,
 'tht': 6927,
 'incident': 3664,
 'lei': 4092,
 'prabha': 5373,
 'soryda': 6366,
 'realy': 5637,
 'frm': 3019,
 'heart': 3394,
 'sory': 6365,
 'karnan': 3917,
 'till': 6946,
 '6pm': 600,
 'directly': 2347,
 'goto': 3217,
 'doctor': 2390,
 'adult': 829,
 '18': 321,
 'content': 1996,
 'video': 7335,
 'shortly': 6154,
 'mode': 4573,
 'men': 4464,
 'left': 4085,
 'happen': 3336,
 'de': 2206,
 'vote': 7377,
 'sing': 6210,
 'along': 922,
 'stars': 6479,
 'karaoke': 3916,
 'link': 4149,
 'download': 2443,
 'clear': 1843,
 'movies': 4627,
 'dvd': 2509,
 'copies': 2021,
 'pretty': 5421,
 'case': 1676,
 'scenario': 5972,
 'brah': 1486,
 'yup': 7785,
 'paragon': 5094,
 'havent': 3370,
 'decided': 2220,
 'whether': 7536,
 'hee': 3401,
 'yar': 7723,
 'wanted': 7429,
 'scold': 5979,
 'yest': 7744,
 'late': 4040,
 'zhong': 7791,
 'se': 6002,
 'qing': 5540,
 'act': 795,
 'watching': 7448,
 'tv': 7131,
 'valentines': 7294,
 'early': 2520,
 'hundreds': 3570,
 'handsomes': 3327,
 'beauties': 1284,
 'thought': 6909,
 'off': 4911,
 'aunties': 1151,
 'uncles': 7184,
 '1st': 338,
 'slept': 6260,
 'thinkthis': 6895,
 'pm': 5288,
 'dangerous': 2177,
 'aunty': 1153,
 'bffs': 1348,
 'carly': 1669,
 'quick': 5552,
 'gettin': 3134,
 'rdy': 5613,
 'ship': 6128,
 'comp': 1931,
 'when': 7527,
 'dad': 2163,
 'prob': 5448,
 'reach': 5615,
 'guess': 3280,
 'wants': 7431,
 'alone': 921,
 'watch': 7445,
 'subscribed': 6603,
 'service': 6065,
 '10': 256,
 '82324': 652,
 'helpline': 3417,
 '08706091795': 88,
 'started': 6482,
 'pray': 5387,
 'ideas': 3610,
 'guys': 3294,
 'forward': 2975,
 '74355': 610,
 'xmas': 7700,
 'iscoming': 3767,
 '500': 533,
 'cd': 1701,
 'gift': 3141,
 'vouchers': 7381,
 'entry': 2634,
 '100': 257,
 'weekly': 7490,
 'draw': 2454,
 'music': 4675,
 '87066': 683,
 'tnc': 6981,
 'beautiful': 1285,
 'truth': 7105,
 'against': 858,
 'gravity': 3244,
 'read': 5621,
 'carefully': 1662,
 'our': 5026,
 'feels': 2826,
 'light': 4127,
 'someone': 6333,
 'heavy': 3399,
 'leaves': 4080,
 'headache': 3380,
 'use': 7266,
 'hour': 3531,
 'sick': 6185,
 'hunny': 3574,
 'wot': 7654,
 '2nite': 415,
 'goin': 3184,
 'town': 7052,
 'jus': 3895,
 'pub': 5506,
 'instead': 3718,
 'chillin': 1796,
 'mo': 4558,
 'bedroom': 1297,
 'jen': 3834,
 'won': 7623,
 'costa': 2036,
 'del': 2246,
 'sol': 6324,
 '5000': 534,
 'await': 1171,
 'collection': 1906,
 '09050090044': 172,
 'toclaim': 6988,
 'sae': 5909,
 'tc': 6774,
 'pobox334': 5294,
 'stockport': 6523,
 'sk38xh': 6236,
 'cost': 2035,
 'max10mins': 4413,
 'bitch': 1379,
 'shall': 6096,
 'avalarr': 1162,
 'hollalater': 3484,
 'wonders': 7627,
 '7th': 629,
 '6th': 601,
 'style': 6589,
 '5th': 561,
 '4th': 524,
 'personality': 5186,
 '3rd': 472,
 'nature': 4726,
 '2nd': 413,
 'lovely': 4248,
 'friendship': 3016,
 'morning': 4609,
 'protect': 5488,
 'yourself': 7771,
 'threats': 6914,
 'sib': 6183,
 'never': 4775,
 'asks': 1104,
 'sensitive': 6052,
 'information': 3692,
 'like': 4129,
 'passwords': 5126,
 'atm': 1129,
 'pin': 5238,
 'thru': 6925,
 'email': 2586,
 'share': 6104,
 'password': 5125,
 'anybody': 997,
 'maneesha': 4363,
 'were': 7511,
 'satisfied': 5952,
 'experience': 2732,
 'toll': 7003,
 'birthday': 1376,
 'may': 4416,
 'dreams': 2458,
 'true': 7098,
 'valued': 7299,
 'customer': 2145,
 'pleased': 5273,
 'advise': 834,
 'following': 2935,
 'recent': 5656,
 'review': 5803,
 '1500': 304,
 'bonus': 1432,
 'prize': 5443,
 '09066364589': 233,
 '8th': 716,
 'campus': 1631,
 'two': 7141,
 'cum': 2130,
 'wnt': 7615,
 'bmw': 1418,
 'urgently': 7254,
 'vry': 7383,
 'urgent': 7253,
 'hv': 3585,
 'shortage': 6150,
 'lacs': 4008,
 'source': 6373,
 'arng': 1072,
 'dis': 2352,
 'lil': 4135,
 'fever': 2837,
 'wkend': 7604,
 'journey': 3876,
 'terrible': 6820,
 'huge': 3559,
 'log': 4196,
 'marking': 4379,
 'shock': 6140,
 'leh': 4091,
 'cos': 2033,
 'shuhui': 6177,
 'leona': 4098,
 'almost': 920,
 'reaction': 5620,
 'getting': 3135,
 'sales': 5921,
 'executive': 2719,
 'shifad': 6121,
 'raised': 5576,
 'complaint': 1941,
 'him': 3445,
 'message': 4474,
 'attracts': 1141,
 'brothas': 1535,
 'wow': 7662,
 'didn': 2317,
 'mean': 4428,
 'once': 4956,
 'gave': 3095,
 'boston': 1451,
 'changed': 1730,
 'search': 6004,
 'location': 4190,
 'nyc': 4886,
 'cuz': 2155,
 'signin': 6195,
 'page': 5066,
 'says': 5967,
 'transfer': 7068,
 'withdraw': 7595,
 'anyhow': 998,
 'loan': 4187,
 'purpose': 5524,
 '75': 611,
 '000': 1,
 'homeowners': 3488,
 'tenants': 6810,
 'previously': 5424,
 'refused': 5690,
 '0800': 47,
 '1956669': 327,
 'replied': 5747,
 'management': 4358,
 'plus': 5285,
 'bank': 1224,
 'wednesday': 7482,
 'half': 3314,
 'freemsg': 2999,
 'buffy': 1560,
 '25': 373,
 'satisfy': 5953,
 'feeling': 2824,
 'randy': 5593,
 'pix': 5246,
 'qlynnbv': 5542,
 'help08700621170150p': 3413,
 'txts': 7150,
 'soul': 6368,
 'fire': 2883,
 'spark': 6387,
 'flame': 2903,
 'big': 1357,
 'rawring': 5604,
 'xoxo': 7701,
 'makes': 4345,
 'most': 4613,
 'ip': 3751,
 'address': 813,
 'test': 6826,
 'considering': 1987,
 'computer': 1952,
 'minecraft': 4507,
 'server': 6064,
 'tot': 7042,
 'stay': 6494,
 'sch': 5974,
 'cutie': 2152,
 'goes': 3181,
 'here': 3424,
 'wales': 7410,
 'kinda': 3959,
 'hills': 3443,
 'shit': 6133,
 'avent': 1166,
 'killed': 3955,
 'myself': 4690,
 'hear': 3390,
 'oh': 4931,
 'hahaha': 3306,
 'brain': 1487,
 'gauti': 3094,
 'sehwag': 6031,
 'odi': 4908,
 'series': 6061,
 'lots': 4234,
 'rakhesh': 5583,
 'nri': 4862,
 'ah': 870,
 'selected': 6033,
 'mum': 4662,
 'robinson': 5836,
 'without': 7598,
 'recharge': 5660,
 'cantdo': 1645,
 'anythingtomorrow': 1006,
 'myparents': 4688,
 'aretaking': 1060,
 'outfor': 5032,
 'meal': 4426,
 'katexxx': 3919,
 'sec': 6008,
 'breaking': 1503,
 'cstore': 2112,
 'opener': 4977,
 'ringtone': 5822,
 'poly': 5315,
 'eg': 2557,
 ...}

In [20]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
np.where(X_train_np[0]!=0)

(array([ 912,  985, 1055, 1099, 1632, 2506, 2543, 2944, 3106, 3167, 3169,
        3171, 3354, 3979, 4354, 4605, 4858, 4909, 5551, 5817, 5915, 6400,
        6845, 7262, 7365, 7550, 7585, 7760]),)

In [25]:
X_train_np[0][1771]

np.int64(0)

In [26]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [27]:
X_test_cv = v.transform(X_test)

In [28]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       973
           1       0.97      0.96      0.97       142

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [29]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [30]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [31]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [32]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       973
           1       0.97      0.96      0.97       142

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115